name: Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          cmake -DCMAKE_BUILD_TYPE=DEBUG .
          make

      - name: Unit tests
        run: |
          ctest -C Debug -V
          gcov -o CMakeFiles/FlowerExchange.dir/src/* src/*.cpp

      - name: Test Executable
        run: |
          ./FlowerExchangeApp ./test/resources/orders_6.csv
          cat ./execution-report.csv
          diff ./test/resources/execution_rep_6.csv ./execution-report.csv

      - name: Generate CodeCov Report
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
